version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASS
    container_name: fiora-cache-redis
    volumes: 
      - cache:/data

  mongo-db:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    container_name: fiora-mongo-db
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD

volumes:
  mongodb:
  cache:
    driver: local